apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ufrn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ufrn
    app.kubernetes.io/part-of: ci10t-777-0076-app
  name: devfile-sample-ufrn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ufrn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ufrn
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0076-tenant/ci10t-777-0076-app/devfile-sample-ufrn@sha256:0bac4ab29207ac30338abd106bb0f05807c18df3af0ffa7d019139a003667488
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
